import tensorflow as tf
from tensorflow.python.ops import tensor_array_ops, control_flow_ops
import numpy as np


class ROLLOUT(object):
    def __init__(self, generator, update_rate):
        self.generator = generator
        self.update_rate = update_rate

        self.num_emb = self.generator.num_emb
        self.batch_size = self.generator.batch_size
        self.emb_dim = self.generator.emb_dim
        self.hidden_dim = self.generator.hidden_dim
        self.sequence_length = self.generator.sequence_length
        self.start_token = tf.identity(self.generator.start_token)
        self.learning_rate = self.generator.learning_rate

        self.g_embeddings = tf.identity(self.generator.g_embeddings)
        self.g_recurrent_unit = self.create_recurrent_unit()
        # maps h_tm1 to h_t for generator
        self.g_output_unit = self.create_output_unit()
        # maps h_t to o_t (output token logits)

        #######################################################################
        # placeholder definition
        self.x = tf.placeholder(
            tf.int32, shape=[self.batch_size, self.sequence_length])
        # sequence of tokens generated by generator
        self.given_num = tf.placeholder(tf.int32)

        # processed for batch
        with tf.device("/cpu:0"):
            self.processed_x = tf.transpose(tf.nn.embedding_lookup(
                self.g_embeddings, self.x), perm=[1, 0, 2])
            # seq_length x batch_size x emb_dim

        ta_emb_x = tensor_array_ops.TensorArray(
            dtype=tf.float32, size=self.sequence_length)
        ta_emb_x = ta_emb_x.unstack(self.processed_x)

        ta_x = tensor_array_ops.TensorArray(
            dtype=tf.int32, size=self.sequence_length)
        ta_x = ta_x.unstack(tf.transpose(self.x, perm=[1, 0]))
        ######################################################################

        self.h0 = tf.zeros([self.batch_size, self.hidden_dim])
        self.h0 = tf.stack([self.h0, self.h0])

        gen_x = tensor_array_ops.TensorArray(
            dtype=tf.int32, size=self.sequence_length,
            dynamic_size=False, infer_shape=True)

        # When current index i < given_num, use the provided tokens as the input
        # at each time step
        def _g_recurrence_1(i, x_t, h_tm1, given_num, gen_x):
            h_t = self.g_recurrent_unit(x_t, h_tm1)  # hidden_memory_tuple
            x_tp1 = ta_emb_x.read(i)
            gen_x = gen_x.write(i, ta_x.read(i))
            return i + 1, x_tp1, h_t, given_num, gen_x

        # When current index i >= given_num, start roll-out, use the output as
        # time step t as the input at time step t+1
        def _g_recurrence_2(i, x_t, h_tm1, given_num, gen_x):
            h_t = self.g_recurrent_unit(x_t, h_tm1)  # hidden_memory_tuple
            o_t = self.g_output_unit(h_t)  # batch x vocab , logits not prob
            log_prob = tf.log(tf.nn.softmax(o_t))
            next_token = tf.cast(tf.reshape(
                tf.multinomial(log_prob, 1), [self.batch_size]), tf.int32)
            x_tp1 = tf.nn.embedding_lookup(self.g_embeddings, next_token)
            # batch x emb_dim
            gen_x = gen_x.write(i, next_token)  # indices, batch_size
            return i + 1, x_tp1, h_t, given_num, gen_x

        i, x_t, h_tm1, given_num, self.gen_x = control_flow_ops.while_loop(
            cond=lambda i, _1, _2, given_num, _4: i < given_num,
            body=_g_recurrence_1,
            loop_vars=(tf.constant(0, dtype=tf.int32),
                       tf.nn.embedding_lookup(
                           self.g_embeddings, self.start_token),
                       self.h0, self.given_num, gen_x))

        _, _, _, _, self.gen_x = control_flow_ops.while_loop(
            cond=lambda i, _1, _2, _3, _4: i < self.sequence_length,
            body=_g_recurrence_2,
            loop_vars=(i, x_t, h_tm1, given_num, self.gen_x))

        self.gen_x = self.gen_x.stack()  # seq_length x batch_size
        self.gen_x = tf.transpose(self.gen_x, perm=[1, 0])
        # batch_size x seq_length

    def get_reward(self, sess, input_x, input_xs, rollout_num, discriminator):
        rewards = []
        for i in range(rollout_num):
            for given_num in range(1, 20):
                feed = {self.x: input_x, self.given_num: given_num}
                samples = sess.run(self.gen_x, feed)
                feed = {
                    discriminator.dis_input_x: samples,
                    discriminator.dis_input_xs: input_xs,
                    discriminator.dropout_keep_prob: 1.0
                }
                ypred_for_auc = sess.run(discriminator.dis_ypred_for_auc, feed)
                ypred = np.array([item[1] for item in ypred_for_auc])
                if i == 0:
                    rewards.append(ypred)
                else:
                    rewards[given_num - 1] += ypred

            # the last token reward
            feed = {
                discriminator.dis_input_x: input_x,
                discriminator.dis_input_xs: input_xs,
                discriminator.dropout_keep_prob: 1.0
            }
            ypred_for_auc = sess.run(discriminator.dis_ypred_for_auc, feed)
            ypred = np.array([item[1] for item in ypred_for_auc])
            if i == 0:
                rewards.append(ypred)
            else:
                rewards[19] += ypred

        rewards = np.transpose(np.array(rewards)) / (1.0 * rollout_num)
        # batch_size x seq_length
        return rewards

    def create_recurrent_unit(self):
        # Weights and Bias for input and hidden tensor
        self.Wi = tf.identity(self.generator.Wi)
        self.Ui = tf.identity(self.generator.Ui)
        self.bi = tf.identity(self.generator.bi)

        self.Wf = tf.identity(self.generator.Wf)
        self.Uf = tf.identity(self.generator.Uf)
        self.bf = tf.identity(self.generator.bf)

        self.Wog = tf.identity(self.generator.Wog)
        self.Uog = tf.identity(self.generator.Uog)
        self.bog = tf.identity(self.generator.bog)

        self.Wc = tf.identity(self.generator.Wc)
        self.Uc = tf.identity(self.generator.Uc)
        self.bc = tf.identity(self.generator.bc)

        def unit(x, hidden_memory_tm1):
            previous_hidden_state, c_prev = tf.unstack(hidden_memory_tm1)

            # Input Gate
            i = tf.sigmoid(
                tf.matmul(x, self.Wi) +
                tf.matmul(previous_hidden_state, self.Ui) + self.bi
            )

            # Forget Gate
            f = tf.sigmoid(
                tf.matmul(x, self.Wf) +
                tf.matmul(previous_hidden_state, self.Uf) + self.bf
            )

            # Output Gate
            o = tf.sigmoid(
                tf.matmul(x, self.Wog) +
                tf.matmul(previous_hidden_state, self.Uog) + self.bog
            )

            # New Memory Cell
            c_ = tf.nn.tanh(
                tf.matmul(x, self.Wc) +
                tf.matmul(previous_hidden_state, self.Uc) + self.bc
            )

            # Final Memory cell
            c = f * c_prev + i * c_

            # Current Hidden state
            current_hidden_state = o * tf.nn.tanh(c)

            return tf.stack([current_hidden_state, c])

        return unit

    def update_recurrent_unit(self):
        # Weights and Bias for input and hidden tensor
        self.Wi = self.update_rate * self.Wi + (
            1 - self.update_rate) * tf.identity(self.generator.Wi)
        self.Ui = self.update_rate * self.Ui + (
            1 - self.update_rate) * tf.identity(self.generator.Ui)
        self.bi = self.update_rate * self.bi + (
            1 - self.update_rate) * tf.identity(self.generator.bi)

        self.Wf = self.update_rate * self.Wf + (
            1 - self.update_rate) * tf.identity(self.generator.Wf)
        self.Uf = self.update_rate * self.Uf + (
            1 - self.update_rate) * tf.identity(self.generator.Uf)
        self.bf = self.update_rate * self.bf + (
            1 - self.update_rate) * tf.identity(self.generator.bf)

        self.Wog = self.update_rate * self.Wog + (
            1 - self.update_rate) * tf.identity(self.generator.Wog)
        self.Uog = self.update_rate * self.Uog + (
            1 - self.update_rate) * tf.identity(self.generator.Uog)
        self.bog = self.update_rate * self.bog + (
            1 - self.update_rate) * tf.identity(self.generator.bog)

        self.Wc = self.update_rate * self.Wc + (
            1 - self.update_rate) * tf.identity(self.generator.Wc)
        self.Uc = self.update_rate * self.Uc + (
            1 - self.update_rate) * tf.identity(self.generator.Uc)
        self.bc = self.update_rate * self.bc + (
            1 - self.update_rate) * tf.identity(self.generator.bc)

        def unit(x, hidden_memory_tm1):
            previous_hidden_state, c_prev = tf.unstack(hidden_memory_tm1)

            # Input Gate
            i = tf.sigmoid(
                tf.matmul(x, self.Wi) +
                tf.matmul(previous_hidden_state, self.Ui) + self.bi
            )

            # Forget Gate
            f = tf.sigmoid(
                tf.matmul(x, self.Wf) +
                tf.matmul(previous_hidden_state, self.Uf) + self.bf
            )

            # Output Gate
            o = tf.sigmoid(
                tf.matmul(x, self.Wog) +
                tf.matmul(previous_hidden_state, self.Uog) + self.bog
            )

            # New Memory Cell
            c_ = tf.nn.tanh(
                tf.matmul(x, self.Wc) +
                tf.matmul(previous_hidden_state, self.Uc) + self.bc
            )

            # Final Memory cell
            c = f * c_prev + i * c_

            # Current Hidden state
            current_hidden_state = o * tf.nn.tanh(c)

            return tf.stack([current_hidden_state, c])

        return unit

    def create_output_unit(self):
        self.Wo = tf.identity(self.generator.Wo)
        self.bo = tf.identity(self.generator.bo)

        def unit(hidden_memory_tuple):
            hidden_state, c_prev = tf.unstack(hidden_memory_tuple)
            # hidden_state : batch x hidden_dim
            logits = tf.matmul(hidden_state, self.Wo) + self.bo
            # output = tf.nn.softmax(logits)
            return logits

        return unit

    def update_output_unit(self):
        self.Wo = self.update_rate * self.Wo + (
            1 - self.update_rate) * tf.identity(self.generator.Wo)
        self.bo = self.update_rate * self.bo + (
            1 - self.update_rate) * tf.identity(self.generator.bo)

        def unit(hidden_memory_tuple):
            hidden_state, c_prev = tf.unstack(hidden_memory_tuple)
            # hidden_state : batch x hidden_dim
            logits = tf.matmul(hidden_state, self.Wo) + self.bo
            # output = tf.nn.softmax(logits)
            return logits

        return unit

    def update_params(self):
        self.g_embeddings = tf.identity(self.generator.g_embeddings)
        self.g_recurrent_unit = self.update_recurrent_unit()
        self.g_output_unit = self.update_output_unit()
